### ISSUE TITLE
Clean DocumentationCache

### ISSUE THREAD

**Issue by Vest** [niklasberglund/xcode-clean.sh#4]
Hello,

Thank you for your script. It is very helpful.
On my Mac I have found the folder (see the title), but I do not know whether it is safe to delete it or not. I can extend your script and add this folder, but before doing this, can you please tell me whether it is safe to delete it :) If yes, I will create the PR.

p.s. I am simply afraid of deleting it blindly.

Thanks,
Vest

**Comment by niklasberglund** [comment]
Interesting! Honestly didn't know of it until now. Is it taking up much space for you? My _DocumentationCache_ dir is taking up 131kb. Maybe mine is so lightweight because I haven't downloaded any additional documentation. Glad you find the script useful 😊

**Comment by Vest** [comment]
Well… mine is bigger ~140 MB. Not gigabytes, but I am just curious. I didn't download the documentation. Probably this comes from the online help.

**Comment by niklasberglund** [comment]
Also curious to know whether it can be removed, but as it doesn't take up that much space it's not a good fit for the script I think. Trying to focus on clearing the large directories taking up much disk space.

**Comment by cagnulein** [comment]
mine is 1,23 GB

**Comment by Yang-Xijie** [comment]
```
$ pwd
/Users/yangxijie/Library/Developer/Xcode/DocumentationCache
$ ls
v187 v203 v207 v213 v216
$ tree -L 2
.
├── v187
│   ├── 12.5
│   └── 12.5.1
├── v203
│   └── 13.1
├── v207
│   └── 13.2.1
├── v213
│   └── 13.3
└── v216
    └── 13.4.1
```

2.26GB total

**Comment by huyz** [comment]
Anyone know whether it's safe to delete?

**Comment by Yang-Xijie** [comment]
@huyz Not sure whether it is safe... However, if you upgrade your Xcode to a new version (eg. 15.1), the older versions (eg. 15.0, 15.0.1) of the documentation **might** be removed safely.

```
$ tree -L 2 ~/Library/Developer/Xcode/DocumentationCache
/Users/yxj/Library/Developer/Xcode/DocumentationCache
├── v243
│   ├── 15.0
│   └── 15.0.1
└── v247
    └── 15.1
6 directories, 0 files
```
